config/routes.rb
Rails.application.routes.draw do
  root 'candles#index'

  resources :candles
  get '/product', to: 'candles#product', as: '/product'
  get '/blog', to: 'candles#blog', as: '/blog'
  get '/giving_back', to:'candles#giving_back', as: '/giving_back'
  get '/near_you', to: 'candles#near_you', as: '/near_you'
  get '/contact', to: 'candles#contact', as: '/contact'

end

# get 'mixtapes_find_single_mixtape', to: 'mixtapes#find_single_mixtape'
# get 'mixtapes_users_mixtapes', to: 'mixtapes#users_mixtapes'

app/models/candle.rb
class Candle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candles_controller.rb
class CandlesController < ApplicationController
  def index
    @candles = Candle.all
  end

  def show
    @candle = Candle.find(params[:id])
    @candle = @candle.present?
  end

  def create
    @candle = Candle.new(candle_params)
    if @candle.save
      redirect_to candles_path
    else
      render :new
    end
  end

  def new
    @candles = Candle.new
  end

  def edit
    @candle = Candle.find(params[:id])
  end

  def update
    @candle = Candle.find(params[:id])

    if @candle.update(candle_params)
      redirect_to candles_path
    else
      render :edit
    end
  end

  def destroy
    @candle = Candle.find(params[:id])
    @candle.destroy
    redirect_to candles_path
  end



  def candle_params
    params.require(:candle).permit(:title, :body, :price)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candles_helper.rb
module CandlesHelper
end

app/views/candles/blog.html.erb
<h1>Blog</h1>
<p>Lorem Khaled Ipsum is a major key to success. Let’s see what Chef Dee got that they don’t want us to eat. A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm. Watch your back, but more importantly when you get out the shower, dry your back, it’s a cold world out there. We don’t see them, we will never see them. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The other day the grass was brown, now it’s green because I ain’t give up. Never surrender.

Bless up. Cloth talk. The key is to enjoy life, because they don’t want you to enjoy life. I promise you, they don’t want you to jetski, they don’t want you to smile. They will try to close the door on you, just open it. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion! Stay focused. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed.
</p>

app/views/candles/contact.html.erb
<h1>Contact</h1>
<p>Learning is cool, but knowing is better, and I know the key to success. The key to success is to keep your head above the water, never give up. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. Special cloth alert. The key is to drink coconut, fresh coconut, trust me. They will try to close the door on you, just open it. They don’t want us to win. I told you all this before, when you have a swimming pool, do not use chlorine, use salt water, the healing, salt water is the healing.

Another one. I’m up to something. Don’t ever play yourself. Always remember in the jungle there’s a lot of they in there, after you overcome they, you will make it to paradise. How’s business? Boomin. They key is to have every key, the key to open every door. The key to more success is to get a massage once a week, very important, major key, cloth talk. They don’t want us to win. We don’t see them, we will never see them. They don’t want us to win.

The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. Special cloth alert. Bless up. I told you all this before, when you have a swimming pool, do not use chlorine, use salt water, the healing, salt water is the healing. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. Celebrate success right, the only way, apple. The key to success is to keep your head above the water, never give up.
</p>

app/views/candles/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @candle do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/candles/giving_back.html.erb
<h1>Giving Back</h1>
<p>They don’t want us to win. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm. Find peace, life is like a water fall, you’ve gotta flow. We don’t see them, we will never see them.

Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. Mogul talk. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. They don’t want us to win. I told you all this before, when you have a swimming pool, do not use chlorine, use salt water, the healing, salt water is the healing. You smart, you loyal, you a genius. You do know, you do know that they don’t want you to have lunch. I’m keeping it real with you, so what you going do is have lunch. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key.

Egg whites, turkey sausage, wheat toast, water. Of course they don’t want us to eat our breakfast, so we are going to enjoy our breakfast. It’s important to use cocoa butter. It’s the key to more success, why not live smooth? Why live rough? Another one. They don’t want us to eat. A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail.

A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm. Wraith talk. Special cloth alert. I’m up to something. Cloth talk. I’m up to something. Egg whites, turkey sausage, wheat toast, water. Of course they don’t want us to eat our breakfast, so we are going to enjoy our breakfast. You do know, you do know that they don’t want you to have lunch. I’m keeping it real with you, so what you going do is have lunch.
</p>

app/views/candles/index.html.erb
        
<h1> Just.BE Candles </h1>
<p><%= link_to 'New Candle', new_candle_path %></p>

<!-- <script>
    $(document).ready(function(){
      $('.carousel').carousel();
      $('.carousel.carousel-slider').carousel({fullWidth: true});
    });
</script> -->



<div class=" ">
  <div class="card">
    <div class="row">
      <div class="col s8 m8 l8">
        <div class="carousel carousel-slider">
          <a class="carousel-item" href="#one!"><img src="https://lorempixel.com/800/400/food/1"></a>
          <a class="carousel-item" href="#two!"><img src="https://lorempixel.com/800/400/food/2"></a>
          <a class="carousel-item" href="#three!"><img src="https://lorempixel.com/800/400/food/3"></a>
          <a class="carousel-item" href="#four!"><img src="https://lorempixel.com/800/400/food/4"></a>
        </div>
      </div>
      <div class="col s4 m4 l4">
        <h3>Our Purpose</h3>
        <p>Lorem Khaled Ipsum is a major key to success. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. I’m up to something. Cloth talk. The key to more success is to have a lot of pillows. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. Congratulations, you played yourself. The key to more success is to have a lot of pillows. Special cloth alert. Hammock talk come soon.
        </p>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
        <% @candles.each do |candle| %>
          <div>
            <div class="col s12 m6 l4 card deep-purple lighten-3 hoverable">
              <div class="card-content white-text">
                <h2 class="center"><%= candle.title %></h2>
                <h5 class="center"><%= candle.body %></h5>
                <h5 class="center">$<%= candle.price %></h5>
                  <div class="row">
                    <hr>
                    <div class="col s4 center">
                      <%= link_to 'Show', candle_path(candle) %>
                    </div>
                    <div class="col s4 center">
                      <%= link_to 'Edit', edit_candle_path(candle) %>
                    </div>
                    <div class="col s4 center">
                      <%= link_to 'Destroy', candle, method: :delete %>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        <% end %> 
  </div>
</div>

app/views/candles/near_you.html.erb
<h1>Near You</h1>
<p>

Major Keys to Success

Find peace, life is like a water fall, you’ve gotta flow. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. Give thanks to the most high. Life is what you make it, so let’s make it. Wraith talk. The key to more success is to get a massage once a week, very important, major key, cloth talk. Look at the sunset, life is amazing, life is beautiful, life is what you make it. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion! They will try to close the door on you, just open it.

Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. They don’t want us to win. Congratulations, you played yourself. Life is what you make it, so let’s make it. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. Look at the sunset, life is amazing, life is beautiful, life is what you make it.

I told you all this before, when you have a swimming pool, do not use chlorine, use salt water, the healing, salt water is the healing. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. It’s important to use cocoa butter. It’s the key to more success, why not live smooth? Why live rough? How’s business? Boomin. Don’t ever play yourself. In life there will be road blocks but we will over come it. Special cloth alert.

I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The key is to drink coconut, fresh coconut, trust me. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. The key is to drink coconut, fresh coconut, trust me. The key to more success is to have a lot of pillows. The key to more success is to have a lot of pillows. The key to more success is to have a lot of pillows. It’s important to use cocoa butter. It’s the key to more success, why not live smooth? Why live rough?

Fan luv. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. In life there will be road blocks but we will over come it. I told you all this before, when you have a swimming pool, do not use chlorine, use salt water, the healing, salt water is the healing.

Hammock talk come soon. Let’s see what Chef Dee got that they don’t want us to eat. Give thanks to the most high. Stay focused. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. Every chance I get, I water the plants, Lion! You smart, you loyal, you a genius. Give thanks to the most high. Cloth talk. Congratulations, you played yourself. Eliptical talk. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion!

Special cloth alert. The other day the grass was brown, now it’s green because I ain’t give up. Never surrender. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Fan luv. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed.

Cloth talk. Let’s see what Chef Dee got that they don’t want us to eat. Cloth talk. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Give thanks to the most high. Eliptical talk. Special cloth alert. Hammock talk come soon. Eliptical talk. Look at the sunset, life is amazing, life is beautiful, life is what you make it.

Wraith talk. In life there will be road blocks but we will over come it. Cloth talk. How’s business? Boomin. Hammock talk come soon. They don’t want us to eat. Egg whites, turkey sausage, wheat toast, water. Of course they don’t want us to eat our breakfast, so we are going to enjoy our breakfast. Hammock talk come soon. How’s business? Boomin. Mogul talk. They never said winning was easy. Some people can’t handle success, I can.

Life is what you make it, so let’s make it. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. They key is to have every key, the key to open every door. Look at the sunset, life is amazing, life is beautiful, life is what you make it. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. In life there will be road blocks but we will over come it. Find peace, life is like a water fall, you’ve gotta flow.

</p>

app/views/candles/new.html.erb
<%= render 'layouts/newcandle' %>

app/views/candles/product.html.erb
<h1>Product</h1>
<p>We the best. Stay focused. Always remember in the jungle there’s a lot of they in there, after you overcome they, you will make it to paradise. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. You smart, you loyal, you a genius. To succeed you must believe. When you believe, you will succeed. They don’t want us to win. Look at the sunset, life is amazing, life is beautiful, life is what you make it. Hammock talk come soon. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed.
</p>

<p><%= link_to 'New Candle', new_candle_path %></p>

<div class="container">
  <div class="row">
        <% @candles.each do |candle| %>
          <div>
            <div class="col s12 m6 l4 card deep-purple lighten-3 hoverable">
              <div class="card-content white-text">
                <h2 class="center"><%= candle.title %></h2>
                <h5 class="center"><%= candle.body %></h5>
                <h5 class="center">$<%= candle.price %></h5>
                  <div class="row">
                    <hr>
                    <div class="col s4 center">
                      <%= link_to 'Show', candle_path(candle) %>
                    </div>
                    <div class="col s4 center">
                      <%= link_to 'Edit', edit_candle_path(candle) %>
                    </div>
                    <div class="col s4 center">
                      <%= link_to 'Destroy', candle, method: :delete %>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        <% end %> 
  </div>
</div>

app/views/candles/show.html.erb
<h1>Candle</h1>
<h2><%= @candle.title %></h2>
<h3><%= @candle.body %></h3>
<h3><%= @candle.price %></h3>
<%= link_to 'Back', candles_path %>


<h1 class="center"> Candle </h1>

<div class="container">
  <div class="row">
    <div class="col s12 m12 l12 center">
      <div class="col s4 m4 l4">
        <p>Title</p>
      </div>
      <div class="col s4 m4 l4">
        <p>Body</p>
      </div>
      <div class="col s4 m4 l4">
        <p>Price</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m12 l12 center">
      <div class="col s4 m4 l4">
        <h4 class="show"><%= @candle.title %></h4>
      </div>
      <div class="col s4 m4 l4">
        <h4 class="show"><%= @candle.body %></h4>
      </div>
      <div class="col s4 m4 l4">
        <h4 class="show"><%= @candle.price %></h4>
      </div>
    </div>
  </div>
</div>

<div class="center">

  <h5><%= link_to 'Back', candles_path %></h5>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Just.BE Candles</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <div>
          <div class="col s2 m2 l2">
            <a href="#!">
              <i class="fa fa-behance fa-lg"></i>
            </a>
          </div>
          <div class="col s2 m2 l2">
            <a href="#!">
              <i class="fa fa-pinterest-p fa-lg"></i>
            </a>
          </div>
          <div class="col s2 m2 l2">
            <a href="#!">
              <i class="fa fa-twitter fa-lg"></i>
            </a>
          </div>
          <div class="col s2 m2 l2">
            <a href="#!">
              <i class="fa fa-facebook fa-lg"></i>
            </a>
          </div>
          <div class="col s2 m2 l2">
            <a href="#!">
              <i class="fa fa-linkedin fa-lg"></i>
            </a>
          </div>

        </div>
      </div>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2017 Copyright All Rights Reserved
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
          <%= link_to 'Our Purpose', root_path %>  
        </li>
        <li>
          <%= link_to 'Product', product_path %>
        </li>
        <li>
          <%= link_to 'Blog', blog_path %>
        </li>
        <li>
          <%= link_to 'Giving Back', giving_back_path %>
        </li>
        <li>
          <%= link_to 'Near You', near_you_path %>
        </li>
        <li>
          <%= link_to 'Contact', contact_path %>
        </li>
      </ul>
    </div>
  </nav>

app/views/layouts/_newcandle.html.erb
<h1> New Candle </h1>
<%= form_for Candle.new do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JbCandles</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
      <%= render 'layouts/navbar' %>
      <div class="container">
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
  </body>
</html>